alias ...='cd ../..'
alias ....='cd ../../..'
alias lf="ls -F"
alias ll="ls -l"
alias ls="ls -G"
alias du="du -h"
alias df="df -h"
alias rm='rm -i'
alias cp='cp -i'
alias mv='mv -i'
alias mkdir='mkdir -p'
alias vi="/usr/local/bin/vim"
alias safari="open -a Safari"
alias itunes="open -a iTunes"
alias prev="open -a Preview"
alias evernote="open -a Evernote"
alias clipstudio="open -a 'CLIP STUDIO PAINT'"
alias quicktimeplayer="open -a 'QuickTime Player'"
